"""
SHENRON Quickstart
One command produces a complete evidence bundle from a fresh clone.
No prior setup required -- uses the committed demo artifact.
"""
import json
from datetime import datetime, timezone
from pathlib import Path

DEMO_ARTIFACT  = Path(__file__).resolve().parents[1] / "artifacts" / "demo" / "shenron_demo_run.jsonl"
SIGMA_DIR      = Path(__file__).resolve().parents[1] / "sigma" / "rules"
ASSUMPTION_DIR = Path(__file__).resolve().parents[1] / "assumptions" / "examples"


def run_quickstart(out_dir=None, verbose=True):
    from core.sigma.evaluator import evaluate_sigma_rule
    from core.assumptions.validator import validate_assumption
    from core.reports.html_report import generate_html_report
    from core.assumptions.loader import load_artifacts
    from collections import Counter

    out = Path(out_dir) if out_dir else Path("reports") / "demo"
    out.mkdir(parents=True, exist_ok=True)

    events_path = str(DEMO_ARTIFACT)
    if not DEMO_ARTIFACT.exists():
        print("  [!] Demo artifact not found. Run: python3 shenron.py --run persistence")
        return {}

    ts = datetime.now(timezone.utc).isoformat()[:19]
    results = {}

    def _p(msg):
        if verbose:
            print(f"  {msg}")

    _p(f"SHENRON Quickstart - {ts} UTC")
    _p(f"Artifact: {events_path}")
    _p("")

    # Step 1: Sigma
    _p("[ 1/4 ] Sigma rule validation...")
    sigma_results = []
    sigma_lines   = []
    if SIGMA_DIR.exists():
        for rp in sorted(SIGMA_DIR.rglob("*.yml")):
            r = evaluate_sigma_rule(str(rp), events_path)
            sigma_results.append(r.to_dict())
            mark = {"TRIGGERED":"+","PARTIAL":"~","NOT_TRIGGERED":"-","UNSUPPORTED":"?"}.get(r.verdict.value," ")
            line = f"  [{mark}] {r.verdict.value:15s}  {r.rule_title}"
            sigma_lines.append(line)
            _p(f"   [{mark}] {r.verdict.value:15s}  {r.rule_title}")

    sigma_report = out / "sigma_validation.txt"
    sigma_report.write_text(
        "SHENRON Sigma Validation - " + ts + " UTC\n"
        "Artifact: " + events_path + "\n\n"
        + "\n".join(sigma_lines) + "\n"
    )
    results["sigma"] = sigma_results
    _p(f"   -> {sigma_report}")
    _p("")

    # Step 2: Assumptions
    _p("[ 2/4 ] Assumption validation...")
    assumption_results = []
    assumption_lines   = []
    if ASSUMPTION_DIR.exists():
        for ap in sorted(ASSUMPTION_DIR.glob("*.yaml")):
            r = validate_assumption(str(ap), events_path)
            assumption_results.append(r.to_dict())
            oos  = f" OOS:{r.out_of_scope_violations}" if r.out_of_scope_violations else ""
            line = f"  {r.assumption_id:<40} {r.status.value}{oos}"
            assumption_lines.append(line)
            _p(f"   {r.assumption_id:<40} {r.status.value}{oos}")

    assumption_report = out / "assumption_validation.txt"
    assumption_report.write_text(
        "SHENRON Assumption Validation - " + ts + " UTC\n"
        "Artifact: " + events_path + "\n\n"
        + "\n".join(assumption_lines) + "\n"
    )
    results["assumptions"] = assumption_results
    _p(f"   -> {assumption_report}")
    _p("")

    # Step 3: Navigator
    _p("[ 3/4 ] ATT&CK Navigator layer...")
    arts  = load_artifacts(events_path)
    mitre = Counter()
    for a in arts:
        techs = a.get("mitre_techniques", [])
        if isinstance(techs, str):
            techs = [techs]
        for t in techs:
            mitre[t] += 1

    sigma_verdict = {}
    for r in sigma_results:
        for det in r.get("detections", []):
            for fm in det.get("field_matches", []):
                if fm.get("field") == "mitre_technique" and fm.get("matched"):
                    tech = fm.get("expected", "").upper()
                    if tech:
                        sigma_verdict[tech] = r.get("verdict", "UNKNOWN")

    COLOR_MAP = {
        "TRIGGERED":     "#22c55e",
        "PARTIAL":       "#f59e0b",
        "NOT_TRIGGERED": "#ef4444",
        "UNSUPPORTED":   "#94a3b8",
    }

    navigator_techniques = []
    for tech, count in mitre.items():
        verdict = sigma_verdict.get(tech.upper(), "NOT_TRIGGERED")
        color   = COLOR_MAP.get(verdict, "#94a3b8")
        navigator_techniques.append({
            "techniqueID": tech,
            "score":       count,
            "color":       color,
            "comment":     "SHENRON: " + str(count) + " artifact(s) | Sigma: " + verdict,
            "enabled":     True,
        })

    navigator_layer = {
        "name":        "SHENRON Coverage",
        "versions":    {"attack": "14", "navigator": "4.9"},
        "domain":      "enterprise-attack",
        "description": "Generated by SHENRON - " + ts + " UTC",
        "techniques":  navigator_techniques,
        "gradient":    {"colors": ["#ffffff", "#22c55e"], "minValue": 0, "maxValue": 10},
        "legendItems": [
            {"label": "TRIGGERED",     "color": "#22c55e"},
            {"label": "PARTIAL",       "color": "#f59e0b"},
            {"label": "NOT_TRIGGERED", "color": "#ef4444"},
        ],
        "metadata": [],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#1e293b",
    }

    navigator_path = out / "attack_navigator_layer.json"
    navigator_path.write_text(json.dumps(navigator_layer, indent=2))
    results["navigator"] = str(navigator_path)
    _p(f"   {len(navigator_techniques)} techniques mapped")
    _p(f"   -> {navigator_path}")
    _p("")

    # Step 4: HTML report
    _p("[ 4/4 ] HTML report...")
    report_data = {
        "run_id":         "quickstart",
        "campaign_name":  "demo",
        "timestamp":      ts,
        "safety":         {"verdict": "PASS", "violations": []},
        "coverage":       {"score": 0.0, "verdict": "DEMO"},
        "findings":       [a for a in arts if a.get("detection_opportunities")][:50],
        "mitre_coverage": {t: {"count": n} for t, n in mitre.items()},
    }

    html_path = generate_html_report(
        report_data,
        output_path        = str(out / "shenron_report.html"),
        sigma_results      = sigma_results,
        assumption_results = assumption_results,
    )
    results["html"] = html_path
    _p(f"   -> {html_path}")
    _p("")

    _p("=" * 58)
    _p("Quickstart complete.")
    _p("")
    _p(f"  Sigma rules evaluated : {len(sigma_results)}")
    _p(f"  Assumptions validated : {len(assumption_results)}")
    _p(f"  MITRE techniques      : {len(navigator_techniques)}")
    _p("")
    _p("  Output files:")
    _p(f"    {sigma_report}")
    _p(f"    {assumption_report}")
    _p(f"    {navigator_path}")
    _p(f"    {html_path}")
    _p("")
    _p("  Next steps:")
    _p(f"    open {html_path}")
    _p(f"    Import {navigator_path} into ATT&CK Navigator")
    _p("")
    _p("  Observable adversarial behavior, not portable adversarial procedure.")
    _p("=" * 58)

    results["out_dir"] = str(out)
    return results
