from datetime import datetime, timezone
from pathlib import Path
from core.assumptions.model import AssumptionResult, ClaimStatus, ClaimType
from core.config import get_report_dir


def generate_scope_report(result: AssumptionResult, all_artifacts: list,
                           output_path: str = None) -> str:
    observed_techniques, observed_layers = set(), set()
    for art in all_artifacts:
        for f in ["mitre_techniques", "technique"]:
            val = art.get(f)
            if isinstance(val, str):
                observed_techniques.add(val.upper())
            elif isinstance(val, list):
                for v in val:
                    observed_techniques.add(str(v).upper())
        if art.get("layer"):
            observed_layers.add(art["layer"])

    c2_techs     = {"T1071","T1095","T1572","T1090","T1132"}
    lateral      = {"T1021","T1570","T1135","T1046"}
    cred         = {"T1003","T1110","T1555","T1552"}
    exfil        = {"T1041","T1048","T1567"}
    not_observed = []
    if not observed_techniques & c2_techs:     not_observed.append("command and control behavior")
    if not observed_techniques & lateral:      not_observed.append("lateral movement")
    if not observed_techniques & cred:         not_observed.append("credential access")
    if not observed_techniques & exfil:        not_observed.append("exfiltration")

    lines = [
        f"# SHENRON Scope Report",
        f"",
        f"**Assumption:** `{result.assumption_id}`",
        f"**Artifact:** `{result.artifact_file}`",
        f"**Generated:** {datetime.now(timezone.utc).isoformat()[:19]} UTC",
        f"**Verdict:** {result.status.value}",
        "", "---", "",
        "## What this artifact contains", "",
        f"Synthetic telemetry from **{len(observed_layers)} simulation layers**.", "",
    ]
    if observed_techniques:
        lines.append("Observed ATT&CK techniques:"); lines.append("")
        for t in sorted(observed_techniques):
            lines.append(f"- `{t}`")
    lines += ["", "---", "", "## What this artifact does not contain", ""]
    for item in not_observed:
        lines.append(f"- {item}")
    lines += ["", "---", "", "## Safe conclusion", ""]
    for s in result.safe_conclusion.split(". "):
        if s.strip():
            lines.append(f"{s.strip()}."); lines.append("")
    lines += ["---", "",
              "*Generated by SHENRON — Observable adversarial behavior, not portable adversarial procedure.*"]

    content = "\n".join(lines)
    if output_path is None:
        out_dir = get_report_dir() / "assumptions"
        out_dir.mkdir(parents=True, exist_ok=True)
        fname = f"scope_{result.assumption_id}_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.md"
        output_path = str(out_dir / fname)
    Path(output_path).write_text(content)
    return output_path


def update_assumption_index(result: AssumptionResult) -> str:
    out_dir = get_report_dir() / "assumptions"
    out_dir.mkdir(parents=True, exist_ok=True)
    index_path = out_dir / "index.md"
    entries = []
    if index_path.exists():
        for line in index_path.read_text().splitlines():
            if line.startswith("| ") and "assumption_id" not in line and "---" not in line and "Run |" not in line:
                entries.append(line)
    run_id   = str(len(entries) + 1).zfill(3)
    date     = result.timestamp[:10]
    artifact = Path(result.artifact_file).name
    entries.append(
        f"| {run_id} | {result.assumption_id} | {result.status.value} | "
        f"{result.supported_count} | {result.unsupported_count} | {artifact} | {date} |"
    )
    header = ["# SHENRON Assumption Audit Index", "",
              "| Run | Assumption | Status | Supported | Unsupported | Artifact | Date |",
              "|-----|------------|--------|-----------|-------------|----------|------|"]
    index_path.write_text("\n".join(header + entries) + "\n")
    return str(index_path)
